### PR TITLE
request: add watchit to ipfs-ecosystem

### PR DESCRIPTION
**Pull request by geolffreym**
Please add watchit to ipfs-ecosystem
https://github.com/ZorrillosDev/watchit-app

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@geolffreym Can you please give others access to push commits to your PR?

**Comment by geolffreym** [comment]
Hi @jessicaschilling i am following this guide to allow access to my PR https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork. Is this what do you need? Thank yout

**Comment by jessicaschilling** [comment]
Yes, please!

**Comment by geolffreym** [comment]
Yes, @jessicaschilling actually i am trying that but I do not see the checkbox to allow writing to my PR, is it possible that it is a configuration on your side?

**Comment by geolffreym** [comment]
moved to https://github.com/ipfs/ecosystem-directory/pull/175

**Pull request closed without merging**
