### PR TITLE
Feat: Showcase View

### PR DESCRIPTION
**Pull request by amanda-agency-undone**
Navigate to: https://localhost:20000/showcase

**Query params:**
`category` taxonomy slug
`md` minimum projects with a tag to display in a medium block. _default 10_
`lg` minimum projects with a tag to display in a large block.  _default 25_

### CODE REVIEW

**Comment by orvn** [comment]
@amanda-agency-undone: Can we make sure to grab the icon, not the logo (for each project)? The icons are the square logos.

**Comment by timelytree** [comment]
@amanda-agency-undone can you rename the `zero.vue` layout to `showcase.vue` instead? This way we know it exists for the purpose of the showcase view? Also "Zero" is the name of our Nuxt-based boilerplate (like "Void" for our WP projects), so there's a minor naming conflict there 😅

Oh one more thing, every component/page/layout requires this as the absolute minimium:

```js
<script>
export default {
  name: 'LayoutZero'
}
</script>
```

can you stick that block under `<template>` in the `zero.vue` layout as well?

**Comment by timelytree** [comment]
Oh also @amanda-agency-undone let's add `@/static/showcase-data.json` to `.gitignore` since it's a dynamically generated file and doesn't need to be + shouldn't be committed to the repo 👌🏼

**Comment by timelytree** [comment]
Oh @amanda-agency-undone found 1 more thing 😬 (screenshot below)

Screen Shot 2021-07-26 at 16 56 35

**Comment by timelytree** [comment]
Some things have changed a little as of the merging of #201 into this PR. Refer to #201 description. As well, `showcase-data.json` has been moved to `@/content/data/`.

**Comment by timelytree** [comment]
@orvn all of this looks great to me → did you have anything else that needed tweaking/testing?

**Comment by D3AS8A** [comment]
@amanda-agency-undone, did the url change for the latest build? 

I'm using https://bafybeievog7zd2btdtixfxl7zvubf4snmiucgbeucuu6t7tnxewekia6gi.on.fleek.co/showcase/?category=focus

**Comment by amanda-agency-undone** [comment]
> @amanda-agency-undone, did the url change for the latest build?
> 
> I'm using https://bafybeievog7zd2btdtixfxl7zvubf4snmiucgbeucuu6t7tnxewekia6gi.on.fleek.co/showcase/?category=focus

@D3AS8A The routing has been updated since the last build. It's working locally, but seems to not be in the build.

**Comment by amanda-agency-undone** [comment]
> @amanda-agency-undone, did the url change for the latest build?
> 
> I'm using https://bafybeievog7zd2btdtixfxl7zvubf4snmiucgbeucuu6t7tnxewekia6gi.on.fleek.co/showcase/?category=focus

Fixed:
https://bafybeic7ugwm2cgib6zlaqsupl4tktmiz74rlfuply62rexoabgx7sxnja.on.fleek.co/showcase/?category=focus

**Review by D3AS8A — APPROVED** [review]

**Pull request merged**
